# Generated by Django 3.2.20 on 2023-09-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.CharField(default='http://placekitten.com/g/200/300', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bg_color',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange')], max_length=50),
        ),
    ]
